

export const ApiStatusCodes = 
{
    GET_USER_INFO_SUCCESS: 200,
    SIGN_UP_SUCCESS: 201,
    SIGN_IN_SUCCESS: 201,
    ERROR_CONNECT_REFUSED: -4078,
    REFRESH_TOKEN_SUCCESS: 201,
    EDIT_USER_PROFILE: 200,
    LOGOUT_SUCCESS: 201,
}
