


export const metadata = {
    title: 'Advanced Web Project',
    description: 'Generated by create next app',
  }
function LayoutOfUserPages({children})
{
    return(
        <html>
            <head>
                <title>{metadata.title}</title>
            </head>
            <body>
                {children}
            </body>
        </html>
    )
}

export default LayoutOfUserPages